# Generated by Django 3.2.8 on 2021-10-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='y_link',
            new_name='youtube_link',
        ),
    ]
